### ISSUE TITLE
Application hang when accessing game with new schema version

### ISSUE THREAD

**Issue by tyr0wl** [Vermintide-Analytics/Vermintide-Analyzer#1]
I tried out the new pre-release. So far it loads my 53 recorded games since the schema change fine as it seems.
Thank you for your work so far. :)

These are the things that I noticed:

- The first launch got stuck at the "Check directories" step for quite a long time, as in the App was unresponsive. The following launches were fast. I suspect that might have to do with one of my log files being about 5gb duo to a malfunctioning mod logging huge amounts of data.
- Accessing games in the game view window is somewhat slow, having frequent smaller hangs in the app browsing the games.
- On one of my games (07.11.2021 - 17:08), the app seems to hang completely. Process manager showed that it consumes about 10% CPU and RAM consumption increased to over 1gb before I closed it.

Attached is the app data folder of VA including the *.VA files it parsed from the log files. If something is missing, I will gladly provide more information. :)

[Vermintide Analyzer.zip](https://github.com/Vermintide-Analytics/Vermintide-Analyzer/files/7499235/Vermintide.Analyzer.zip)

**Comment by Vermintide-Analytics** [comment]
Addressing each bullet sequentially:

- There should be no reason for it to get spend any noticeable amount of time on the "Checking Directories" step. That step does less than one might think. All it does is verify that a few folders exist in appdata. Not sure what may have caused this. My only suspicion is that perhaps it was on a later step that could take a while, like "Gathering latest data" which would take some time if there are a lot of console logs to parse through. I tried to avoid the "current step" displayed to the user being out of sync with what is actually being done, but perhaps I didn't get it quite right.
- I moved all of your games into my Games folder to see if there was any slowdown. Perhaps this just comes down to a difference in CPU power, but I do not notice any slowness. Can you describe exactly when you see slowness?
- I looked at the data for this file and it looked normal, and I was able to open this game without any problem. Does this problem persist after restarting the Analyzer? Can you describe exactly what happens? Does the window for the game pop up but is empty? Is some data present but not others? etc.

**Comment by tyr0wl** [comment]
I made a gif to demonstrate the behavior. I start the application and select the game in question, and it becomes not responsive.

![Vermintide Analyzer](https://user-images.githubusercontent.com/6159764/140825302-f3e32066-9882-44f4-b650-82d9920c0a40.gif)

The slowness can be described best as a general "sluggishness". This only starts when I open one of the game views and can be seen as I try to change the chart in the bottom right corner. At first there is only a delay, but then it completely hangs up.
Please note that I do not need to click anything for the application to become unresponsive in this game view.

I also opened task manager, and my CPU is barely active. The app itself stays at a constant 10% while the RAM usage keeps increasing. I am using an i7-8700 as CPU.

**Comment by tyr0wl** [comment]
I ran a version where I commented out `ConstructSeries();` in `GameViewWindow.xaml.cs` and the problem vanished completely. So it seems to have to do with the charts.

Not sure what it exactly is, but something I did not mention before is that the charts do not look right to me. At the very least, the plotting for the axis seems off. Here is a screenshot with a less extreme example:

![image](https://user-images.githubusercontent.com/6159764/140829120-1e2d5f9b-46e0-4465-b005-fd1750466b4c.png)

Another little thing is, that `Avg Crit Multi` shows `xNaN `in the gif above.

**Comment by Vermintide-Analytics** [comment]
Aha, I see what is happening here. Observe what the "Damage Taken" chart *should* look like for your game, and then compare it to the version in your gif (thank you so much for that by the way, I couldn't ask for better reporting!).
![image](https://user-images.githubusercontent.com/87454156/140828457-808f9ce2-4761-411a-b46b-65257bb3f9f6.png)

This has to do with how numbers are parsed in different cultures. The app is taking your culture and using it when reading numbers from the data. For example, in
`CurrentHealth|0,269.99176025391`
the 2nd number (temporary health) is interpreted as 26 trillion.

When I was designing the charts, I made some assumptions about data, like assuming values would not be in the trillions. What this means is that the chart is trying to draw billions of axis markers and tickmarks.
I should be able to fix this by forcing a specific culture when parsing numbers.

Thanks again for the detailed report!

**Comment by tyr0wl** [comment]
Oh noes culture info stricks again! Had my fair share with that, happy that I could help. :)

**Comment by Vermintide-Analytics** [comment]
As for the crit multiplier being NaN, that is in some sense expected because it says you did not crit any times during that game. No actual number could go there and be correct, so it either needs to be blank or say NaN.

**Comment by Vermintide-Analytics** [comment]
I was able to reproduce the issue by overriding the culture to de-DE as an example. I then was no longer able to see the issue after some changes.

The fix is available in [v1.1.1](https://github.com/Vermintide-Analytics/Vermintide-Analyzer/releases/tag/v1.1.1)
Let me know if it is still a problem for you or not.

**Comment by tyr0wl** [comment]
Working as expected now. :) Great work. 👍

If the behavior with `NaN` is intended, that is fine by me. Can just be a bit confusing at first.
